default: &default
  adapter: <%= ENV['DATABASE_ADAPTER'] %>
  encoding: unicode
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  host: localhost

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default